"""add_career_impacts_table

Revision ID: 2307e6a068f4
Revises: h1i2j3k4l5m6
Create Date: 2026-07-05 01:03:21.376961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2307e6a068f4'
down_revision = 'h1i2j3k4l5m6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_impacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quote', sa.String(length=500), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_impacts_id'), 'career_impacts', ['id'], unique=False)
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.drop_index('media_id', table_name='project_images')
    op.create_foreign_key(None, 'project_images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index('thumbnail_id', table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('thumbnail_id', 'projects', ['thumbnail_url'], unique=False)
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.create_index('media_id', 'project_images', ['image_url'], unique=False)
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_index(op.f('ix_career_impacts_id'), table_name='career_impacts')
    op.drop_table('career_impacts')
    # ### end Alembic commands ###
